### ISSUE TITLE
Camera Overlay disappearing randomly

### ISSUE THREAD

**Issue by joe-f** [appcelerator-modules/ti.barcode#77] opened 2018-08-01 09:27 UTC
@hansemannn On latest iOS version, we're seeing the camera overlay view randomly disappear after a period of time if you leave the scanner open but don't scan a code. 

Sometimes 5 seconds after opening, other times up to a minute, very random. Thought it might have been to do with touch or orientation, but have been unable to reproduce it reliably. 

It's just a simple view with a label or two on it. We've tried setting a zIndex on the overlay too, but that didn't make a difference.

Any ideas?

**Comment by hansemannn** [comment] 2018-08-01 09:32
latest = 2.0.0?

**Comment by hansemannn** [comment] 2018-08-01 09:32
cc @vijaysingh-axway

**Comment by vijaysingh-axway** [comment] 2018-08-01 10:30
@joe-f  Is it happening on 2.0.0? I tried at my end but unable to reproduce. Can you please share a small test case? Thanks!

**Comment by joe-f** [comment] 2018-08-01 11:50
@hansemannn @vijaysingh-axway Using ios-1.10.2, that is the newest version under releases on Github. Is there a newer version?

I can provide a test case for it, we're seeing it on iPhone X.

**Comment by joe-f** [comment] 2018-08-01 13:14
I've done some further testing , we can now reliably get the overlay to disappear after changing device orientation several times with the scanner open. 

This includes changing from portrait to a phone lying flat on a desk, can sometimes be 1 orientation change or 4-5 times to trigger it.

**Comment by hansemannn** [comment] 2018-08-01 16:53
@joe-f We refactored the module in v2.0.0, which is currently in testing.

**Comment by hansemannn** [comment] 2018-08-01 16:54
Should be fixed in https://github.com/appcelerator-modules/ti.barcode/releases/tag/ios-2.0.0

**Closed by hansemannn** 2018-08-01 16:54 UTC

**Comment by joe-f** [comment] 2018-08-06 09:33
@hansemannn The overlay is still disappearing for us using 2.0.0. Video here: https://www.youtube.com/watch?v=eimGSLbyiMA

Not always as quickly as that, seems to be a random amount of time before it goes away, even without any orientation change.

Thoughts?

**Comment by vijaysingh-axway** [comment] 2018-08-06 10:00
@joe-f  I have created ticket, https://jira.appcelerator.org/browse/MOD-2445, in Jira. Can you please provide the simple test case? Thanks!

**Comment by hansemannn** [comment] 2018-08-08 08:37
@joe-f Can you please try v2.0.1 from the releases tab?
