### ISSUE TITLE
iOS 8.3, overlay does not respond to clicks.

### ISSUE THREAD

**Issue by annakozy2011** [appcelerator-modules/ti.barcode#19] opened 2015-05-29 07:56 UTC
I upgraded my iPad to iOS 8.3, and there is a bug - overlay does not respond to any clicks (nor the buttons or anything). 

Any idea how to solve this?

**Comment by annakozy2011** [comment] 2015-05-29 07:59
PS: it only occurs on device. Simulator works fine.

**Comment by annakozy2011** [comment] 2015-07-14 14:08
On iPad 8.3 it did work after update of XCode. 

Now the same is happening on iPhone 6 (only) with iOS 8.4

**Comment by beaurushton** [comment] 2015-09-30 01:32
Yeah overlay is not working on iOS9 :(

**Comment by m1ga** [comment] 2015-11-06 13:11
any update here?

**Comment by hansemannn** [comment] 2016-01-05 15:25
Is this issue only happening on iOS8+?

**Comment by hansemannn** [comment] 2016-01-05 17:03
Hey guys, please try https://github.com/appcelerator-modules/ti.barcode/pull/32 which should resolve this issue, too.

**Comment by hansemannn** [comment] 2017-08-23 08:05
Closing as duplicate of #41 where it will be addressed.

**Closed by hansemannn** 2017-08-23 08:05 UTC
